! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module sql
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: get_ODBCVER
 public :: SQLAllocConnect
 public :: SQLAllocEnv
 public :: SQLAllocHandle
 public :: SQLAllocStmt
 public :: SQLBindCol
 public :: SQLBindParam
 public :: SQLCancel
 public :: SQLCancelHandle
 public :: SQLCloseCursor
 public :: SQLColAttribute
 public :: SQLColumns
 public :: SQLConnect
 public :: SQLCopyDesc
 public :: SQLDataSources
 public :: SQLDescribeCol
 public :: SQLDisconnect
 public :: SQLEndTran
 public :: SQLError
 public :: SQLExecDirect
 public :: SQLExecute
 public :: SQLFetch
 public :: SQLFetchScroll
 public :: SQLFreeConnect
 public :: SQLFreeEnv
 public :: SQLFreeHandle
 public :: SQLFreeStmt
 public :: SQLGetConnectAttr
 public :: SQLGetConnectOption
 public :: SQLGetCursorName
 public :: SQLGetData
 public :: SQLGetDescField
 public :: SQLGetDescRec
 public :: SQLGetDiagField
 public :: SQLGetDiagRec
 public :: SQLGetEnvAttr
 public :: SQLGetFunctions
 public :: SQLGetInfo
 public :: SQLGetStmtAttr
 public :: SQLGetStmtOption
 public :: SQLGetTypeInfo
 public :: SQLNumResultCols
 public :: SQLParamData
 public :: SQLPrepare
 public :: SQLPutData
 public :: SQLRowCount
 public :: SQLSetConnectAttr
 public :: SQLSetConnectOption
 public :: SQLSetCursorName
 public :: SQLSetDescField
 public :: SQLSetDescRec
 public :: SQLSetEnvAttr
 public :: SQLSetParam
 public :: SQLSetStmtAttr
 public :: SQLSetStmtOption
 public :: SQLSpecialColumns
 public :: SQLStatistics
 public :: SQLTables
 public :: SQLTransact

! WRAPPER DECLARATIONS
interface
function swigc_ODBCVER_get() &
bind(C, name="_wrap_ODBCVER_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function SQLAllocConnect(environmenthandle, connectionhandle) &
bind(C, name="SQLAllocConnect") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: environmenthandle
type(c_ptr), intent(out) :: connectionhandle
integer(c_short) :: fresult
end function

function SQLAllocEnv(environmenthandle) &
bind(C, name="SQLAllocEnv") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(out) :: environmenthandle
integer(c_short) :: fresult
end function

function SQLAllocHandle(handletype, inputhandle, outputhandle) &
bind(C, name="SQLAllocHandle") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_short), intent(in), value :: handletype
type(c_ptr), intent(in), value :: inputhandle
type(c_ptr), intent(out) :: outputhandle
integer(c_short) :: fresult
end function

function SQLAllocStmt(connectionhandle, statementhandle) &
bind(C, name="SQLAllocStmt") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
type(c_ptr), intent(out) :: statementhandle
integer(c_short) :: fresult
end function

function SQLBindCol(statementhandle, columnnumber, targettype, targetvalue, bufferlength, strlen_or_ind) &
bind(C, name="SQLBindCol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: columnnumber
integer(c_short), intent(in), value :: targettype
type(c_ptr), intent(in), value :: targetvalue
integer(c_long), intent(in), value :: bufferlength
integer(c_long), intent(out) :: strlen_or_ind
integer(c_short) :: fresult
end function

function SQLBindParam(statementhandle, parameternumber, valuetype, parametertype, lengthprecision, parameterscale, &
  parametervalue, strlen_or_ind) &
bind(C, name="SQLBindParam") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: parameternumber
integer(c_short), intent(in), value :: valuetype
integer(c_short), intent(in), value :: parametertype
integer(c_long), intent(in), value :: lengthprecision
integer(c_short), intent(in), value :: parameterscale
type(c_ptr), intent(in), value :: parametervalue
integer(c_long), intent(out) :: strlen_or_ind
integer(c_short) :: fresult
end function

function SQLCancel(statementhandle) &
bind(C, name="SQLCancel") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short) :: fresult
end function

function SQLCancelHandle(handletype, inputhandle) &
bind(C, name="SQLCancelHandle") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_short), intent(in), value :: handletype
type(c_ptr), intent(in), value :: inputhandle
integer(c_short) :: fresult
end function

function SQLCloseCursor(statementhandle) &
bind(C, name="SQLCloseCursor") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short) :: fresult
end function

function SQLColAttribute(statementhandle, columnnumber, fieldidentifier, characterattribute, bufferlength, stringlength, &
  numericattribute) &
bind(C, name="SQLColAttribute") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: columnnumber
integer(c_short), intent(in), value :: fieldidentifier
type(c_ptr), intent(in), value :: characterattribute
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: stringlength
integer(c_long), intent(out) :: numericattribute
integer(c_short) :: fresult
end function

function SQLColumns(statementhandle, catalogname, namelength1, schemaname, namelength2, tablename, namelength3, columnname, &
  namelength4) &
bind(C, name="SQLColumns") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: catalogname
integer(c_short), intent(in), value :: namelength1
character(kind=c_char) :: schemaname
integer(c_short), intent(in), value :: namelength2
character(kind=c_char) :: tablename
integer(c_short), intent(in), value :: namelength3
character(kind=c_char) :: columnname
integer(c_short), intent(in), value :: namelength4
integer(c_short) :: fresult
end function

function SQLConnect(connectionhandle, servername, namelength1, username, namelength2, authentication, namelength3) &
bind(C, name="SQLConnect") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
character(kind=c_char) :: servername
integer(c_short), intent(in), value :: namelength1
character(kind=c_char) :: username
integer(c_short), intent(in), value :: namelength2
character(kind=c_char) :: authentication
integer(c_short), intent(in), value :: namelength3
integer(c_short) :: fresult
end function

function SQLCopyDesc(sourcedeschandle, targetdeschandle) &
bind(C, name="SQLCopyDesc") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: sourcedeschandle
type(c_ptr), intent(in), value :: targetdeschandle
integer(c_short) :: fresult
end function

function SQLDataSources(environmenthandle, direction, servername, bufferlength1, namelength1, description, bufferlength2, &
  namelength2) &
bind(C, name="SQLDataSources") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: environmenthandle
integer(c_short), intent(in), value :: direction
character(kind=c_char) :: servername
integer(c_short), intent(in), value :: bufferlength1
integer(c_short), intent(out) :: namelength1
character(kind=c_char) :: description
integer(c_short), intent(in), value :: bufferlength2
integer(c_short), intent(out) :: namelength2
integer(c_short) :: fresult
end function

function SQLDescribeCol(statementhandle, columnnumber, columnname, bufferlength, namelength, datatype, columnsize, &
  decimaldigits, nullable) &
bind(C, name="SQLDescribeCol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: columnnumber
character(kind=c_char) :: columnname
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: namelength
integer(c_short), intent(out) :: datatype
integer(c_long), intent(out) :: columnsize
integer(c_short), intent(out) :: decimaldigits
integer(c_short), intent(out) :: nullable
integer(c_short) :: fresult
end function

function SQLDisconnect(connectionhandle) &
bind(C, name="SQLDisconnect") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_short) :: fresult
end function

function SQLEndTran(handletype, handle, completiontype) &
bind(C, name="SQLEndTran") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_short), intent(in), value :: handletype
type(c_ptr), intent(in), value :: handle
integer(c_short), intent(in), value :: completiontype
integer(c_short) :: fresult
end function

function SQLError(environmenthandle, connectionhandle, statementhandle, sqlstate, nativeerror, messagetext, bufferlength, &
  textlength) &
bind(C, name="SQLError") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: environmenthandle
type(c_ptr), intent(in), value :: connectionhandle
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: sqlstate
integer(c_int), intent(out) :: nativeerror
character(kind=c_char) :: messagetext
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: textlength
integer(c_short) :: fresult
end function

function SQLExecDirect(statementhandle, statementtext, textlength) &
bind(C, name="SQLExecDirect") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: statementtext
integer(c_int), intent(in), value :: textlength
integer(c_short) :: fresult
end function

function SQLExecute(statementhandle) &
bind(C, name="SQLExecute") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short) :: fresult
end function

function SQLFetch(statementhandle) &
bind(C, name="SQLFetch") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short) :: fresult
end function

function SQLFetchScroll(statementhandle, fetchorientation, fetchoffset) &
bind(C, name="SQLFetchScroll") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: fetchorientation
integer(c_long), intent(in), value :: fetchoffset
integer(c_short) :: fresult
end function

function SQLFreeConnect(connectionhandle) &
bind(C, name="SQLFreeConnect") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_short) :: fresult
end function

function SQLFreeEnv(environmenthandle) &
bind(C, name="SQLFreeEnv") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: environmenthandle
integer(c_short) :: fresult
end function

function SQLFreeHandle(handletype, handle) &
bind(C, name="SQLFreeHandle") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_short), intent(in), value :: handletype
type(c_ptr), intent(in), value :: handle
integer(c_short) :: fresult
end function

function SQLFreeStmt(statementhandle, option) &
bind(C, name="SQLFreeStmt") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: option
integer(c_short) :: fresult
end function

function SQLGetConnectAttr(connectionhandle, attribute, value, bufferlength, stringlength) &
bind(C, name="SQLGetConnectAttr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_int), intent(in), value :: attribute
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: bufferlength
integer(c_int), intent(out) :: stringlength
integer(c_short) :: fresult
end function

function SQLGetConnectOption(connectionhandle, option, value) &
bind(C, name="SQLGetConnectOption") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_short), intent(in), value :: option
type(c_ptr), intent(in), value :: value
integer(c_short) :: fresult
end function

function SQLGetCursorName(statementhandle, cursorname, bufferlength, namelength) &
bind(C, name="SQLGetCursorName") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: cursorname
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: namelength
integer(c_short) :: fresult
end function

function SQLGetData(statementhandle, columnnumber, targettype, targetvalue, bufferlength, strlen_or_ind) &
bind(C, name="SQLGetData") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: columnnumber
integer(c_short), intent(in), value :: targettype
type(c_ptr), intent(in), value :: targetvalue
integer(c_long), intent(in), value :: bufferlength
integer(c_long), intent(out) :: strlen_or_ind
integer(c_short) :: fresult
end function

function SQLGetDescField(descriptorhandle, recnumber, fieldidentifier, value, bufferlength, stringlength) &
bind(C, name="SQLGetDescField") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: descriptorhandle
integer(c_short), intent(in), value :: recnumber
integer(c_short), intent(in), value :: fieldidentifier
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: bufferlength
integer(c_int), intent(out) :: stringlength
integer(c_short) :: fresult
end function

function SQLGetDescRec(descriptorhandle, recnumber, name, bufferlength, stringlength, type, subtype, length, precision, scale, &
  nullable) &
bind(C, name="SQLGetDescRec") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: descriptorhandle
integer(c_short), intent(in), value :: recnumber
character(kind=c_char) :: name
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: stringlength
integer(c_short), intent(out) :: type
integer(c_short), intent(out) :: subtype
integer(c_long), intent(out) :: length
integer(c_short), intent(out) :: precision
integer(c_short), intent(out) :: scale
integer(c_short), intent(out) :: nullable
integer(c_short) :: fresult
end function

function SQLGetDiagField(handletype, handle, recnumber, diagidentifier, diaginfo, bufferlength, stringlength) &
bind(C, name="SQLGetDiagField") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_short), intent(in), value :: handletype
type(c_ptr), intent(in), value :: handle
integer(c_short), intent(in), value :: recnumber
integer(c_short), intent(in), value :: diagidentifier
type(c_ptr), intent(in), value :: diaginfo
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: stringlength
integer(c_short) :: fresult
end function

function SQLGetDiagRec(handletype, handle, recnumber, sqlstate, nativeerror, messagetext, bufferlength, textlength) &
bind(C, name="SQLGetDiagRec") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_short), intent(in), value :: handletype
type(c_ptr), intent(in), value :: handle
integer(c_short), intent(in), value :: recnumber
character(kind=c_char) :: sqlstate
integer(c_int), intent(out) :: nativeerror
character(kind=c_char) :: messagetext
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: textlength
integer(c_short) :: fresult
end function

function SQLGetEnvAttr(environmenthandle, attribute, value, bufferlength, stringlength) &
bind(C, name="SQLGetEnvAttr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: environmenthandle
integer(c_int), intent(in), value :: attribute
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: bufferlength
integer(c_int), intent(out) :: stringlength
integer(c_short) :: fresult
end function

function SQLGetFunctions(connectionhandle, functionid, supported) &
bind(C, name="SQLGetFunctions") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_short), intent(in), value :: functionid
integer(c_short), intent(out) :: supported
integer(c_short) :: fresult
end function

function SQLGetInfo(connectionhandle, infotype, infovalue, bufferlength, stringlength) &
bind(C, name="SQLGetInfo") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_short), intent(in), value :: infotype
type(c_ptr), intent(in), value :: infovalue
integer(c_short), intent(in), value :: bufferlength
integer(c_short), intent(out) :: stringlength
integer(c_short) :: fresult
end function

function SQLGetStmtAttr(statementhandle, attribute, value, bufferlength, stringlength) &
bind(C, name="SQLGetStmtAttr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_int), intent(in), value :: attribute
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: bufferlength
integer(c_int), intent(out) :: stringlength
integer(c_short) :: fresult
end function

function SQLGetStmtOption(statementhandle, option, value) &
bind(C, name="SQLGetStmtOption") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: option
type(c_ptr), intent(in), value :: value
integer(c_short) :: fresult
end function

function SQLGetTypeInfo(statementhandle, datatype) &
bind(C, name="SQLGetTypeInfo") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: datatype
integer(c_short) :: fresult
end function

function SQLNumResultCols(statementhandle, columncount) &
bind(C, name="SQLNumResultCols") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(out) :: columncount
integer(c_short) :: fresult
end function

function SQLParamData(statementhandle, value) &
bind(C, name="SQLParamData") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
type(c_ptr), intent(out) :: value
integer(c_short) :: fresult
end function

function SQLPrepare(statementhandle, statementtext, textlength) &
bind(C, name="SQLPrepare") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: statementtext
integer(c_int), intent(in), value :: textlength
integer(c_short) :: fresult
end function

function SQLPutData(statementhandle, data, strlen_or_ind) &
bind(C, name="SQLPutData") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
type(c_ptr), intent(in), value :: data
integer(c_long), intent(in), value :: strlen_or_ind
integer(c_short) :: fresult
end function

function SQLRowCount(statementhandle, rowcount) &
bind(C, name="SQLRowCount") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_long), intent(out) :: rowcount
integer(c_short) :: fresult
end function

function SQLSetConnectAttr(connectionhandle, attribute, value, stringlength) &
bind(C, name="SQLSetConnectAttr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_int), intent(in), value :: attribute
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: stringlength
integer(c_short) :: fresult
end function

function SQLSetConnectOption(connectionhandle, option, value) &
bind(C, name="SQLSetConnectOption") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: connectionhandle
integer(c_short), intent(in), value :: option
integer(c_long), intent(in), value :: value
integer(c_short) :: fresult
end function

function SQLSetCursorName(statementhandle, cursorname, namelength) &
bind(C, name="SQLSetCursorName") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: cursorname
integer(c_short), intent(in), value :: namelength
integer(c_short) :: fresult
end function

function SQLSetDescField(descriptorhandle, recnumber, fieldidentifier, value, bufferlength) &
bind(C, name="SQLSetDescField") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: descriptorhandle
integer(c_short), intent(in), value :: recnumber
integer(c_short), intent(in), value :: fieldidentifier
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: bufferlength
integer(c_short) :: fresult
end function

function SQLSetDescRec(descriptorhandle, recnumber, type, subtype, length, precision, scale, data, stringlength, indicator) &
bind(C, name="SQLSetDescRec") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: descriptorhandle
integer(c_short), intent(in), value :: recnumber
integer(c_short), intent(in), value :: type
integer(c_short), intent(in), value :: subtype
integer(c_long), intent(in), value :: length
integer(c_short), intent(in), value :: precision
integer(c_short), intent(in), value :: scale
type(c_ptr), intent(in), value :: data
integer(c_long), intent(out) :: stringlength
integer(c_long), intent(out) :: indicator
integer(c_short) :: fresult
end function

function SQLSetEnvAttr(environmenthandle, attribute, value, stringlength) &
bind(C, name="SQLSetEnvAttr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: environmenthandle
integer(c_int), intent(in), value :: attribute
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: stringlength
integer(c_short) :: fresult
end function

function SQLSetParam(statementhandle, parameternumber, valuetype, parametertype, lengthprecision, parameterscale, &
  parametervalue, strlen_or_ind) &
bind(C, name="SQLSetParam") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: parameternumber
integer(c_short), intent(in), value :: valuetype
integer(c_short), intent(in), value :: parametertype
integer(c_long), intent(in), value :: lengthprecision
integer(c_short), intent(in), value :: parameterscale
type(c_ptr), intent(in), value :: parametervalue
integer(c_long), intent(out) :: strlen_or_ind
integer(c_short) :: fresult
end function

function SQLSetStmtAttr(statementhandle, attribute, value, stringlength) &
bind(C, name="SQLSetStmtAttr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_int), intent(in), value :: attribute
type(c_ptr), intent(in), value :: value
integer(c_int), intent(in), value :: stringlength
integer(c_short) :: fresult
end function

function SQLSetStmtOption(statementhandle, option, value) &
bind(C, name="SQLSetStmtOption") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: option
integer(c_long), intent(in), value :: value
integer(c_short) :: fresult
end function

function SQLSpecialColumns(statementhandle, identifiertype, catalogname, namelength1, schemaname, namelength2, tablename, &
  namelength3, scope, nullable) &
bind(C, name="SQLSpecialColumns") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
integer(c_short), intent(in), value :: identifiertype
character(kind=c_char) :: catalogname
integer(c_short), intent(in), value :: namelength1
character(kind=c_char) :: schemaname
integer(c_short), intent(in), value :: namelength2
character(kind=c_char) :: tablename
integer(c_short), intent(in), value :: namelength3
integer(c_short), intent(in), value :: scope
integer(c_short), intent(in), value :: nullable
integer(c_short) :: fresult
end function

function SQLStatistics(statementhandle, catalogname, namelength1, schemaname, namelength2, tablename, namelength3, unique, &
  reserved) &
bind(C, name="SQLStatistics") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: catalogname
integer(c_short), intent(in), value :: namelength1
character(kind=c_char) :: schemaname
integer(c_short), intent(in), value :: namelength2
character(kind=c_char) :: tablename
integer(c_short), intent(in), value :: namelength3
integer(c_short), intent(in), value :: unique
integer(c_short), intent(in), value :: reserved
integer(c_short) :: fresult
end function

function SQLTables(statementhandle, catalogname, namelength1, schemaname, namelength2, tablename, namelength3, tabletype, &
  namelength4) &
bind(C, name="SQLTables") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: statementhandle
character(kind=c_char) :: catalogname
integer(c_short), intent(in), value :: namelength1
character(kind=c_char) :: schemaname
integer(c_short), intent(in), value :: namelength2
character(kind=c_char) :: tablename
integer(c_short), intent(in), value :: namelength3
character(kind=c_char) :: tabletype
integer(c_short), intent(in), value :: namelength4
integer(c_short) :: fresult
end function

function SQLTransact(environmenthandle, connectionhandle, completiontype) &
bind(C, name="SQLTransact") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: environmenthandle
type(c_ptr), intent(in), value :: connectionhandle
integer(c_short), intent(in), value :: completiontype
integer(c_short) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function get_ODBCVER() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_ODBCVER_get()
swig_result = fresult
end function


end module
