! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module sqlext
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: SQLDriverConnect
 public :: SQLBrowseConnect
 public :: SQLColAttributes
 public :: SQLColumnPrivileges
 public :: SQLDescribeParam
 public :: SQLExtendedFetch
 public :: SQLForeignKeys
 public :: SQLMoreResults
 public :: SQLNativeSql
 public :: SQLNumParams
 public :: SQLParamOptions
 public :: SQLPrimaryKeys
 public :: SQLProcedureColumns
 public :: SQLProcedures
 public :: SQLSetPos
 public :: SQLTablePrivileges
 public :: SQLDrivers
 public :: SQLBindParameter
 public :: SQLSetScrollOptions
 public :: TraceOpenLogFile
 public :: TraceCloseLogFile
 public :: TraceReturn
 public :: TraceVersion
 public :: TraceVSControl
 public :: FireVSDebugEvent
 public :: ODBCSetTryWaitValue
 public :: ODBCGetTryWaitValue

! WRAPPER DECLARATIONS
interface
function SQLDriverConnect(hdbc, hwnd, szconnstrin, cbconnstrin, szconnstrout, cbconnstroutmax, pcbconnstrout, &
  fdrivercompletion) &
bind(C, name="SQLDriverConnect") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hdbc
type(c_ptr), intent(in), value :: hwnd
character(kind=c_char) :: szconnstrin
integer(c_short), intent(in), value :: cbconnstrin
character(kind=c_char) :: szconnstrout
integer(c_short), intent(in), value :: cbconnstroutmax
integer(c_short), intent(out) :: pcbconnstrout
integer(c_short), intent(in), value :: fdrivercompletion
integer(c_short) :: fresult
end function

function SQLBrowseConnect(hdbc, szconnstrin, cbconnstrin, szconnstrout, cbconnstroutmax, pcbconnstrout) &
bind(C, name="SQLBrowseConnect") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hdbc
character(kind=c_char) :: szconnstrin
integer(c_short), intent(in), value :: cbconnstrin
character(kind=c_char) :: szconnstrout
integer(c_short), intent(in), value :: cbconnstroutmax
integer(c_short), intent(out) :: pcbconnstrout
integer(c_short) :: fresult
end function

function SQLColAttributes(hstmt, icol, fdesctype, rgbdesc, cbdescmax, pcbdesc, pfdesc) &
bind(C, name="SQLColAttributes") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_short), intent(in), value :: icol
integer(c_short), intent(in), value :: fdesctype
type(c_ptr), intent(in), value :: rgbdesc
integer(c_short), intent(in), value :: cbdescmax
integer(c_short), intent(out) :: pcbdesc
integer(c_long), intent(out) :: pfdesc
integer(c_short) :: fresult
end function

function SQLColumnPrivileges(hstmt, szcatalogname, cbcatalogname, szschemaname, cbschemaname, sztablename, cbtablename, &
  szcolumnname, cbcolumnname) &
bind(C, name="SQLColumnPrivileges") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
character(kind=c_char) :: szcatalogname
integer(c_short), intent(in), value :: cbcatalogname
character(kind=c_char) :: szschemaname
integer(c_short), intent(in), value :: cbschemaname
character(kind=c_char) :: sztablename
integer(c_short), intent(in), value :: cbtablename
character(kind=c_char) :: szcolumnname
integer(c_short), intent(in), value :: cbcolumnname
integer(c_short) :: fresult
end function

function SQLDescribeParam(hstmt, ipar, pfsqltype, pcbparamdef, pibscale, pfnullable) &
bind(C, name="SQLDescribeParam") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_short), intent(in), value :: ipar
integer(c_short), intent(out) :: pfsqltype
integer(c_long), intent(out) :: pcbparamdef
integer(c_short), intent(out) :: pibscale
integer(c_short), intent(out) :: pfnullable
integer(c_short) :: fresult
end function

function SQLExtendedFetch(hstmt, ffetchtype, irow, pcrow, rgfrowstatus) &
bind(C, name="SQLExtendedFetch") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_short), intent(in), value :: ffetchtype
integer(c_long), intent(in), value :: irow
integer(c_long), intent(out) :: pcrow
integer(c_short), intent(out) :: rgfrowstatus
integer(c_short) :: fresult
end function

function SQLForeignKeys(hstmt, szpkcatalogname, cbpkcatalogname, szpkschemaname, cbpkschemaname, szpktablename, cbpktablename, &
  szfkcatalogname, cbfkcatalogname, szfkschemaname, cbfkschemaname, szfktablename, cbfktablename) &
bind(C, name="SQLForeignKeys") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
character(kind=c_char) :: szpkcatalogname
integer(c_short), intent(in), value :: cbpkcatalogname
character(kind=c_char) :: szpkschemaname
integer(c_short), intent(in), value :: cbpkschemaname
character(kind=c_char) :: szpktablename
integer(c_short), intent(in), value :: cbpktablename
character(kind=c_char) :: szfkcatalogname
integer(c_short), intent(in), value :: cbfkcatalogname
character(kind=c_char) :: szfkschemaname
integer(c_short), intent(in), value :: cbfkschemaname
character(kind=c_char) :: szfktablename
integer(c_short), intent(in), value :: cbfktablename
integer(c_short) :: fresult
end function

function SQLMoreResults(hstmt) &
bind(C, name="SQLMoreResults") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_short) :: fresult
end function

function SQLNativeSql(hdbc, szsqlstrin, cbsqlstrin, szsqlstr, cbsqlstrmax, pcbsqlstr) &
bind(C, name="SQLNativeSql") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hdbc
character(kind=c_char) :: szsqlstrin
integer(c_int), intent(in), value :: cbsqlstrin
character(kind=c_char) :: szsqlstr
integer(c_int), intent(in), value :: cbsqlstrmax
integer(c_int), intent(out) :: pcbsqlstr
integer(c_short) :: fresult
end function

function SQLNumParams(hstmt, pcpar) &
bind(C, name="SQLNumParams") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_short), intent(out) :: pcpar
integer(c_short) :: fresult
end function

function SQLParamOptions(hstmt, crow, pirow) &
bind(C, name="SQLParamOptions") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_long), intent(in), value :: crow
integer(c_long), intent(out) :: pirow
integer(c_short) :: fresult
end function

function SQLPrimaryKeys(hstmt, szcatalogname, cbcatalogname, szschemaname, cbschemaname, sztablename, cbtablename) &
bind(C, name="SQLPrimaryKeys") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
character(kind=c_char) :: szcatalogname
integer(c_short), intent(in), value :: cbcatalogname
character(kind=c_char) :: szschemaname
integer(c_short), intent(in), value :: cbschemaname
character(kind=c_char) :: sztablename
integer(c_short), intent(in), value :: cbtablename
integer(c_short) :: fresult
end function

function SQLProcedureColumns(hstmt, szcatalogname, cbcatalogname, szschemaname, cbschemaname, szprocname, cbprocname, &
  szcolumnname, cbcolumnname) &
bind(C, name="SQLProcedureColumns") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
character(kind=c_char) :: szcatalogname
integer(c_short), intent(in), value :: cbcatalogname
character(kind=c_char) :: szschemaname
integer(c_short), intent(in), value :: cbschemaname
character(kind=c_char) :: szprocname
integer(c_short), intent(in), value :: cbprocname
character(kind=c_char) :: szcolumnname
integer(c_short), intent(in), value :: cbcolumnname
integer(c_short) :: fresult
end function

function SQLProcedures(hstmt, szcatalogname, cbcatalogname, szschemaname, cbschemaname, szprocname, cbprocname) &
bind(C, name="SQLProcedures") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
character(kind=c_char) :: szcatalogname
integer(c_short), intent(in), value :: cbcatalogname
character(kind=c_char) :: szschemaname
integer(c_short), intent(in), value :: cbschemaname
character(kind=c_char) :: szprocname
integer(c_short), intent(in), value :: cbprocname
integer(c_short) :: fresult
end function

function SQLSetPos(hstmt, irow, foption, flock) &
bind(C, name="SQLSetPos") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_long), intent(in), value :: irow
integer(c_short), intent(in), value :: foption
integer(c_short), intent(in), value :: flock
integer(c_short) :: fresult
end function

function SQLTablePrivileges(hstmt, szcatalogname, cbcatalogname, szschemaname, cbschemaname, sztablename, cbtablename) &
bind(C, name="SQLTablePrivileges") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
character(kind=c_char) :: szcatalogname
integer(c_short), intent(in), value :: cbcatalogname
character(kind=c_char) :: szschemaname
integer(c_short), intent(in), value :: cbschemaname
character(kind=c_char) :: sztablename
integer(c_short), intent(in), value :: cbtablename
integer(c_short) :: fresult
end function

function SQLDrivers(henv, fdirection, szdriverdesc, cbdriverdescmax, pcbdriverdesc, szdriverattributes, cbdrvrattrmax, &
  pcbdrvrattr) &
bind(C, name="SQLDrivers") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: henv
integer(c_short), intent(in), value :: fdirection
character(kind=c_char) :: szdriverdesc
integer(c_short), intent(in), value :: cbdriverdescmax
integer(c_short), intent(out) :: pcbdriverdesc
character(kind=c_char) :: szdriverattributes
integer(c_short), intent(in), value :: cbdrvrattrmax
integer(c_short), intent(out) :: pcbdrvrattr
integer(c_short) :: fresult
end function

function SQLBindParameter(hstmt, ipar, fparamtype, fctype, fsqltype, cbcoldef, ibscale, rgbvalue, cbvaluemax, pcbvalue) &
bind(C, name="SQLBindParameter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_short), intent(in), value :: ipar
integer(c_short), intent(in), value :: fparamtype
integer(c_short), intent(in), value :: fctype
integer(c_short), intent(in), value :: fsqltype
integer(c_long), intent(in), value :: cbcoldef
integer(c_short), intent(in), value :: ibscale
type(c_ptr), intent(in), value :: rgbvalue
integer(c_long), intent(in), value :: cbvaluemax
integer(c_long), intent(out) :: pcbvalue
integer(c_short) :: fresult
end function

function SQLSetScrollOptions(hstmt, fconcurrency, crowkeyset, crowrowset) &
bind(C, name="SQLSetScrollOptions") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: hstmt
integer(c_short), intent(in), value :: fconcurrency
integer(c_long), intent(in), value :: crowkeyset
integer(c_short), intent(in), value :: crowrowset
integer(c_short) :: fresult
end function

function TraceOpenLogFile(arg0, arg1, arg2, arg3) &
bind(C, name="TraceOpenLogFile") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: arg0
character(c_char), dimension(*) :: arg1
character(c_char), dimension(*) :: arg2
integer(c_int), intent(in), value :: arg3
integer(c_short) :: fresult
end function

function TraceCloseLogFile(arg0) &
bind(C, name="TraceCloseLogFile") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: arg0
integer(c_short) :: fresult
end function

function TraceReturn(arg0, arg1) &
bind(C, name="TraceReturn") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(c_ptr), intent(in), value :: arg0
integer(c_short) :: arg1
integer(c_short) :: fresult
end function

function TraceVersion() &
bind(C, name="TraceVersion") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_int):: fresult
end function

function TraceVSControl(arg0) &
bind(C, name="TraceVSControl") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_int), intent(in), value :: arg0
integer(c_short) :: fresult
end function

subroutine FireVSDebugEvent(arg0) &
bind(C, name="FireVSDebugEvent")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: arg0
end subroutine

function ODBCSetTryWaitValue(dwvalue) &
bind(C, name="ODBCSetTryWaitValue") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_int), intent(in), value :: dwvalue
integer(c_int):: fresult
end function

function ODBCGetTryWaitValue() &
bind(C, name="ODBCGetTryWaitValue") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(c_int):: fresult
end function

end interface


end module
